remote_theme : mmistakes/minimal-mistakes
minimal_mistakes_skin    : "default"

locale                   : "ko-KR"
title                    : "Keep it real"
title_separator          : "-"
name                     : "Argent"
description              : "For my favorite"
url                      : "https://ddkkinf.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : ddkkinf/ddkkinf.github.io
